# Generated by Django 3.1.3 on 2021-01-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('transfer_audio', models.FileField(default='', upload_to='')),
                ('predict_result', models.CharField(max_length=1000)),
            ],
        ),
    ]
