# Generated by Django 3.1.3 on 2021-01-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_remove_message_predict_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='transfer_audio',
            field=models.FileField(default='output_audio/', upload_to=''),
        ),
    ]
