# Generated by Django 3.1.3 on 2021-01-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_auto_20210123_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='transfer_audio',
            field=models.FileField(default='', upload_to='output_audio/'),
        ),
    ]
