# Generated by Django 3.1.3 on 2020-11-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_wav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadDocumentForm',
        ),
    ]
