# Generated by Django 3.1.3 on 2020-11-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_wav', '0003_auto_20201123_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersong',
            name='audio_file_output',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
