# Generated by Django 3.1.3 on 2021-08-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_wav', '0006_remove_usersong_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersong',
            name='audio_file',
            field=models.FileField(upload_to='output_audio/'),
        ),
    ]
