# Generated by Django 3.1.3 on 2021-09-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_wav', '0007_auto_20210803_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersong',
            name='give_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersong',
            name='audio_file',
            field=models.FileField(upload_to=''),
        ),
    ]
